import * as Joi from 'joi';
export interface ConfigInterface {
  USDT_CONTRACT_ADDRESS: string;
  NODE_ENV: string;
  PORT: string;
  MONGO_LOCAL_URI: string;
  MONGO_CLUSTER_URI: string;
  JWT_TOKEN: string;
  JWT_EXPIRY_TIME: string;
  TWILLIO_AUTH_TOKEN: string;
  TWILLIO_ACCOUNT_SID: string;
  SENDGRID_API_KEY: string;
  EMAIL_FROM: string;
  AWS_ACCESS_KEY: string;
  AWS_SECRET_KEY: string;
  AWS_BUCKET: string;
  AWS_REGION: string;
  CEX_SECRET_KEY: string;
  DB_TYPE: string;
  POSTGRESS_HOST: string;
  POSTGRESS_PORT: string;
  POSTGRESS_USERNAME: string;
  POSTGRESS_PASSWORD: string;
  POSTGRESS_DATABASE: string;
  WALLET_PRIVATE_KEY: string;
  RPC_URL: string;
  MORALIS_PUB_KEY: string;
  PINATA_API_KEY: string;
  PINATA_GATEWAY_TOKEN: string;
  PINATA_JWT_KEY: string;
  PINATA_SECRET_KEY: string;
  BUMPER_WALLET_PRIVATE_KEY: string;
  VOLUME_WALLET_PRIVATE_KEY: string;
}
